import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import { SessionProvider } from 'next-auth/react';
import Navbar from '@/components/navbar';
import { Toaster } from 'sonner';
import { cn } from '@/lib/utils';
import './globals.css';

const fontSans = FontSans({
 subsets: ['latin'],
 variable: '--font-sans',
});

export const metadata: Metadata = {
 title: 'Create Next App',
 description: 'Generated by create next app',
};

export default async function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <SessionProvider>
   <html lang='en'>
    <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
     <Navbar />
     {children}
     <Toaster richColors />
    </body>
   </html>
  </SessionProvider>
 );
}
